stages:
  preprocess_train:
    cmd: preprocess -v -i data/raw/train.csv -o data/processed/train.csv
    deps:
    - src/house_prices/preprocess.py
    - data/raw/train.csv
    outs:
    - data/processed/train.csv
  preprocess_test:
    cmd: preprocess -v -i data/raw/test.csv -o data/processed/test.csv
    deps:
    - src/house_prices/preprocess.py
    - data/raw/test.csv
    outs:
    - data/processed/test.csv
  split:
    cmd: split -v -i data/processed/train.csv -t data/modelling/train.csv -e data/modelling/validation.csv
    params:
    - split.random_state
    - split.test_size
    deps:
    - src/house_prices/split.py
    - data/processed/train.csv
    outs:
    - data/modelling/train.csv
    - data/modelling/validation.csv
  linear_regression:
    cmd: linear_regression -v -i data/modelling/train.csv -o models/linear_regression.joblib
    deps:
    - src/house_prices/ml/linear_regression.py
    - src/house_prices/modelling.py
    - data/modelling/train.csv
    outs:
    - models/linear_regression.joblib
  linear_ridge_regression:
    cmd: linear_ridge_regression -v -i data/modelling/train.csv -o models/linear_ridge_regression.joblib
    deps:
    - src/house_prices/ml/linear_ridge_regression.py
    - src/house_prices/modelling.py
    - data/modelling/train.csv
    outs:
    - models/linear_ridge_regression.joblib
  linear_lasso_regression:
    cmd: linear_lasso_regression -v -i data/modelling/train.csv -o models/linear_lasso_regression.joblib
    deps:
    - src/house_prices/ml/linear_lasso_regression.py
    - src/house_prices/modelling.py
    - data/modelling/train.csv
    outs:
    - models/linear_lasso_regression.joblib
  random_forest:
    cmd: random_forest -v -i data/modelling/train.csv -o models/random_forest.joblib
    deps:
    - src/house_prices/ml/random_forest.py
    - src/house_prices/modelling.py
    - data/modelling/train.csv
    outs:
    - models/random_forest.joblib
