stages:
  preprocess_train:
    cmd: preprocess -v -i data/raw/train.csv -o data/processed/train.csv
    deps:
    - src/house_prices/etl/preprocess.py
    - data/raw/train.csv
    outs:
    - data/processed/train.csv
  preprocess_test:
    cmd: preprocess -v -i data/raw/test.csv -o data/processed/test.csv
    deps:
    - src/house_prices/etl/preprocess.py
    - data/raw/test.csv
    outs:
    - data/processed/test.csv
  split:
    cmd: split -v -i data/processed/train.csv -t data/modelling/train.csv -e data/modelling/validation.csv
    params:
    - split.seed
    - split.test_size
    deps:
    - src/house_prices/etl/split.py
    - data/processed/train.csv
    outs:
    - data/modelling/train.csv
    - data/modelling/validation.csv
  train_lm:
    cmd: train_lm -v -i data/modelling/train.csv -o models/lm.joblib
    deps:
    - src/house_prices/modelling/train_lm.py
    - data/modelling/train.csv
    outs:
    - models/lm.joblib
  train_lm_ridge:
    cmd: train_lm_ridge -v -i data/modelling/train.csv -o models/lm_ridge.joblib
    deps:
    - src/house_prices/modelling/train_lm_ridge.py
    - data/modelling/train.csv
    outs:
    - models/lm_ridge.joblib
